<?php

namespace Smile\EzTFABundle\Repository;

use Smile\EzTFABundle\Entity\TFASMS;

/**
 * TFASMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TFASMSRepository extends \Doctrine\ORM\EntityRepository
{
    public function savePhone($userId, $phone)
    {
        $tfaSMS = new TFASMS();
        $tfaSMS->setUserId($userId);
        $tfaSMS->setPhone($phone);

        $this->getEntityManager()->persist($tfaSMS);
        $this->getEntityManager()->flush();
    }
}
