<?php

namespace Smile\EzTFABundle\Repository;

use Smile\EzTFABundle\Entity\TFASMS;
use eZ\Publish\API\Repository\Values\User\User as APIUser;

/**
 * TFASMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TFASMSRepository extends \Doctrine\ORM\EntityRepository
{
    public function savePhone($userId, $phone)
    {
        $tfaSMS = new TFASMS();
        $tfaSMS->setUserId($userId);
        $tfaSMS->setPhone($phone);

        $this->getEntityManager()->persist($tfaSMS);
        $this->getEntityManager()->flush();
    }

    public function remove(TFASMS $tfaSMS)
    {
        $this->getEntityManager()->remove($tfaSMS);
        $this->getEntityManager()->flush();
    }

    public function purge(APIUser $user)
    {
        /** @var TFASMS[] $tfaSMSs */
        $tfaSMSs = $this->findByUserId($user->id);

        if ($tfaSMSs) {
            foreach ($tfaSMSs as $tfaSMS) {
                $this->getEntityManager()->remove($tfaSMS);
                $this->getEntityManager()->flush();
            }
        }
    }
}
