<?php

namespace Smile\EzTFABundle\Repository;

use Smile\EzTFABundle\Entity\TFAU2F;

/**
 * TFAU2FRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TFAU2FRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveKey($registrationData, $userId, $keyName)
    {
        $tfaU2F = new TFAU2F();
        $tfaU2F->setKeyName($keyName);
        $tfaU2F->setUserId($userId);
        $tfaU2F->setKeyHandle($registrationData->keyHandle);
        $tfaU2F->setPublicKey($registrationData->publicKey);
        $tfaU2F->setCertificate($registrationData->certificate);
        $tfaU2F->setCounter($registrationData->counter);

        $this->getEntityManager()->persist($tfaU2F);
        $this->getEntityManager()->flush();
    }
}
